<?xml version="1.0" encoding="utf-8"?><Database Name="db_9b1fc5_cpc2017e2" Class="DataJakubWoszczynaZad7DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=sql5037.site4now.net;Initial Catalog=db_9b1fc5_cpc2017e2;Persist Security Info=True;User ID=DB_9B1FC5_cpc2017e2_admin" SettingsObjectName="JakubWoszczynaZad7.Properties.Settings" SettingsPropertyName="db_9b1fc5_cpc2017e2ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[JakubWoszczyna-Positions]" Member="JakubWoszczyna_Positions">
    <Type Name="JakubWoszczyna_Position">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="X" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Y" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[JakubWoszczyna-Scores]" Member="JakubWoszczyna_Scores">
    <Type Name="JakubWoszczyna_Score">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlayerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PointsNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>